# Generated by Django 3.0.8 on 2020-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='songscategory',
            name='cover',
            field=models.ImageField(default='default-song.png', upload_to='pics'),
        ),
    ]
