# Generated by Django 3.0.8 on 2020-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200802_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='cover',
            field=models.ImageField(default='default-song.png', upload_to='pics'),
        ),
    ]
