# Generated by Django 3.0.8 on 2020-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200803_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='songscategory',
            name='label',
            field=models.CharField(default='#e74c3c', max_length=50),
        ),
    ]
