# Generated by Django 3.0.8 on 2020-08-10 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0011_auto_20200810_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.songs'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('name', 'user')},
        ),
    ]
