# Generated by Django 3.0.8 on 2020-08-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20200810_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='songss',
        ),
    ]
