# Generated by Django 3.0.8 on 2020-08-14 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0014_auto_20200813_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comments_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replys',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='replys_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replys',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='replys_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
