# Generated by Django 3.0.8 on 2020-08-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_auto_20200814_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='replys',
            options={'ordering': ('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set(),
        ),
    ]
