# Generated by Django 3.0.8 on 2020-08-20 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_auto_20200817_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('-added',)},
        ),
        migrations.AddField(
            model_name='playlist',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
