# Generated by Django 3.0.8 on 2020-08-20 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0017_auto_20200820_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('added',)},
        ),
        migrations.AlterField(
            model_name='songs',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
