# Generated by Django 3.0.8 on 2020-08-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='songs',
        ),
    ]
