# Generated by Django 3.0.8 on 2020-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-user-icon.jpg', upload_to='pics'),
        ),
    ]
